language: ruby

# Enable bundler cache to speed up booting
cache:
  bundler: true
  directories:
    - vendor/bundle
    - public/assets

sudo: required

rvm:
  - 2.3.1

env:
  - RAILS_ENV=test

services:
  - postgresql

#bundler_args: --without development

before_install:
  - openssl aes-256-cbc -K $encrypted_1f12d85304e2_key -iv $encrypted_1f12d85304e2_iv -in config/application.travis.yml.enc -out config/application.travis.yml -d
  - wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xjf phantomjs-2.1.1-linux-x86_64.tar.bz2
  - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
  - sudo mv phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/local/phantomjs/bin/phantomjs

before_script:
  # Install and run BitGoJS, not sure if it's really necessary - it is better to fully ignore bitgo in tests
  - git clone https://github.com/BitGo/BitGoJS.git
  - cd BitGoJS && npm install
  - cd bin && chmod +x bitgo-express
  - nohup node bitgo-express --debug --port 3080 --env prod --bind localhost &
  - cd ../../
  # Copy Travis application config
  - cp config/application.travis.yml config/application.yml
  # Create database and run migrations, seed
  - bundle exec rake sunspot:solr:start
  - bundle exec rake db:create db:schema:load db:migrate # db:seed
  - bundle exec rake assets:precompile

script:
  - bundle exec rspec

notifications:
  slack:
    rooms:
      - youserve:LZx9PuGbnpt7asZw8Kej4f2B#travis_report