test: &default

  # Credentials for REST APIs
  client_id: ASREOEiAqctQzuCskTj3YiytqvTD1t4nQWu79VNMhcTR1p1Oi_XZ2ppeXumbx2OxvPtsHQFrqr13HxvB # EBWKjlELKMYqRNQ6sYvFo64FtaRLRR5BdHEESmha49TM
  client_secret: EAm0GijrfJukzN9cksZfu4TZxRqkNjkCUBzb7MQ4neX1mXOJL53BXtkKNLFeLO1PDl5uHK4MsPC2iE5x  # EO422dn3gQLgDbuwqTjzrFgFtaRLRR5BdHEESmha49TM

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  # app_id: APP-7R8398975V428283R
  username: bruno19850511-facilitator_api1.yahoo.com #jb-us-seller_api1.paypal.com
  password: FE5DVXMBHK7CWVY5  # WX4WTU3S8MY44S7F
  signature: AdEspXkb-VJPlq5cFqemocL7r0hfAGegJYS1u-0vwHoJptyfG1xKwtVz # AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: bruno19850511-facilitator@yahoo.com #  Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

  # verbose_logging: true

development:
  <<: *default

production:
  <<: *default
  mode: sandbox
